services:
  - type: web
    name: inventory-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: postgresql://inventoty_db_user:6zJkwMyaKx2SalktpTF2eGEKZDDV1eaT@dpg-d0ve1qvdiees73cq1ql0-a/inventoty_db
      - key: POSTGRES_POOL_SIZE
        value: 5
      - key: POSTGRES_MAX_OVERFLOW
        value: 10
      - key: POSTGRES_POOL_TIMEOUT
        value: 30
      - key: DEBUG
        value: "False" 